version: "3.8"
services:
  #  db:

  backend_mk:
    build:
      context: .
      dockerfile: jdk.dockerfile
    ports:
      - "8000:8000"
    container_name: app_mk
    depends_on:
      - db_mk
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/compose-postgres
#      - SPRING_DATASOURCE_USERNAME=compose-postgres
#      - SPRING_DATASOURCE_PASSWORD=compose-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./:/app/

  db_mk:
    image: 'postgres:13.1-alpine'
    container_name: db_mk
    environment:
      - POSTGRES_USER=db_mk
      - POSTGRES_PASSWORD=db_mk
      - POSTGRES_DB=db_mk
    ports:
      - "5432:5432"
